package com.freeankit.freenotepad.helper

/**
 * @author Ankit Kumar on 27/07/2018
 */


val REQUEST_CAMERA = 100
val REQUEST_AUDIO = 101
val REQUEST_VIDEO = 102

val MY_PERMISSIONS_REQUEST_READ_EXTERNAL_STORAGE = 1234
val MY_PERMISSIONS_REQUEST_CAMERA = 1235
val MY_PERMISSIONS_REQUEST_CONTACTS = 1236
val MY_PERMISSIONS_REQUEST_LOCATION = 1237

val TARGET_REQUEST_GALLERY = 11111

var PREF_FILE_CONFIG: String = "PREF_FILE_CONFIG"
var EXTRA_KEY_USER: String = "EXTRA_KEY_USER"
var FCM_TOKEN: String = "FCM_TOKEN"
var FIRTIME: String = "FIRTIME"

val TAG = "Ideas"
val RC_SIGN_IN = 9001